### PR TITLE
Danny get pot page

### PR DESCRIPTION
**Pull request by danny-george**
created the framework for a get available sharers page

### CODE REVIEW

**Review by JungwooJang119 — APPROVED** [review]
very well made get pot page! cache files should be ignored in gitignore so shouldnt be a problem

**Comment by jacobcouvillon** [comment]
Looks good!

**Review by JungwooJang119 — APPROVED** [review]
looks great!

**Review by JziTaylor — APPROVED** [review]
Great live demo of this Danny! the page looks good

**Pull request merged**
